experiment: Multitask Learning on Segmentation and Classification of Intracranial Hemorrhage Using CT Scans
exp_name: exp_full_zscore

data:
  img_dir: /home/chris/Downloads/Hemo_Data_Seg/test/images
  seg_dir: /home/chris/Downloads/Hemo_Data_Seg/test/labels
  postfix: nii.gz
  n_samples: 222

model:
  segnet:
    batch_size: 8
    n_batch_per_epoch: 50
    lr: 0.001
    weight_decay: 1e-4
    in_channel: 1
    out_channel: 2
    encode_layers: [16, 48, 96, 192, 384]
    decode_layers: [64, 32, 16, 4]
    stride: [2, 2, 2, 2]
    dropout: 0.4
    norm: instance
    loss_weights: [3.0, 0.0]

  regnet:
    batch_size: 2
    n_batch_per_epoch: 100
    lr: 0.001
    weight_decay: 1e-3
    in_channel: 2
    out_channel: 3
    encode_layers: [16, 32, 32, 32, 32]
    decode_layers: [32, 32, 32, 32, 16, 16]
    stride: [2, 2, 2, 2]
    dropout: 0.4
    norm: instance
    loss_weights: [1e-6, 1e-4, 2.0]

  classnet:
    lr: 5e-5
    n_batch_per_epoch: 80
    weight_decay: 5e-3
    in_channel: 384
    out_channel: 2
    res_channel: 384
    dropout: 0.6

  baseseg:
    batch_size: 4
    lr: 5e-4
    spatial_dim: 3
    in_channel: 1
    out_channel: 2
    channels: [8, 16, 16, 32, 32, 64, 64]
    strides: [1, 2, 1, 2, 1, 2]
    dropout: 0.4
    norm: batch
    act: leakyrelu

train:
  epochs: 300
  val_iter: 1
