name: hem
channels:
- defaults
- conda-forge
dependencies:
- _libgcc_mutex=0.1
- _openmp_mutex=5.1
- asttokens=3.0.0
- bzip2=1.0.8
- ca-certificates=2025.2.25
- comm=0.2.2
- debugpy=1.8.13
- decorator=5.2.1
- exceptiongroup=1.2.2
- executing=2.1.0
- ipykernel=6.29.5
- ipython=8.34.0
- jedi=0.19.2
- jupyter_client=8.6.3
- jupyter_core=5.7.2
- krb5=1.21.3
- ld_impl_linux-64=2.40
- libedit=3.1.20230828
- libffi=3.4.4
- libgcc=14.2.0
- libgcc-ng=14.2.0
- libgomp=14.2.0
- libsodium=1.0.20
- libstdcxx=14.2.0
- libstdcxx-ng=11.2.0
- libuuid=1.41.5
- matplotlib-inline=0.1.7
- ncurses=6.4
- nest-asyncio=1.6.0
- openssl=3.4.1
- packaging=24.2
- parso=0.8.4
- pexpect=4.9.0
- pickleshare=0.7.5
- pip=25.0
- platformdirs=4.3.7
- prompt-toolkit=3.0.50
- psutil=7.0.0
- ptyprocess=0.7.0
- pure_eval=0.2.3
- pygments=2.19.1
- python=3.10.16
- python-dateutil=2.9.0.post0
- python_abi=3.10
- pyzmq=26.3.0
- readline=8.2
- setuptools=75.8.0
- six=1.17.0
- sqlite=3.45.3
- stack_data=0.6.3
- tk=8.6.14
- tornado=6.4.2
- traitlets=5.14.3
- typing_extensions=4.13.0
- wcwidth=0.2.13
- wheel=0.45.1
- xz=5.6.4
- zeromq=4.3.5
- zipp=3.21.0
- zlib=1.2.13
- pip
- pip:
  - absl-py==2.1.0
  - alembic==1.15.1
  - annotated-types==0.7.0
  - antlr4-python3-runtime==4.9.3
  - antspyx==0.5.4
  - asciitree==0.3.3
  - astor==0.8.1
  - attrs==25.1.0
  - beautifulsoup4==4.13.3
  - blinker==1.9.0
  - cachetools==5.5.2
  - certifi==2025.1.31
  - charset-normalizer==3.4.1
  - clearml==1.17.2rc0
  - click==8.1.8
  - cloudpickle==3.1.1
  - colorama==0.4.6
  - coloredlogs==15.0.1
  - colorlog==6.9.0
  - contourpy==1.3.1
  - cucim-cu12==25.2.0
  - cupy-cuda12x==13.4.0
  - cycler==0.12.1
  - databricks-sdk==0.45.0
  - deprecated==1.2.18
  - docker==7.1.0
  - einops==0.8.1
  - fasteners==0.19
  - fastrlock==0.8.3
  - filelock==3.11.0
  - fire==0.7.0
  - flask==3.1.0
  - flatbuffers==25.2.10
  - fonttools==4.56.0
  - fsspec==2025.3.0
  - furl==2.1.4
  - gdown==5.2.0
  - gitdb==4.0.12
  - gitpython==3.1.44
  - google-auth==2.38.0
  - graphene==3.4.3
  - graphql-core==3.2.6
  - graphql-relay==3.2.0
  - greenlet==3.1.1
  - grpcio==1.70.0
  - gunicorn==23.0.0
  - h5py==3.13.0
  - huggingface-hub==0.29.2
  - humanfriendly==10.0
  - idna==3.10
  - imagecodecs==2024.12.30
  - imageio==2.37.0
  - importlib-metadata==8.5.0
  - importlib-resources==6.5.2
  - itk==5.4.2.post1
  - itk-core==5.4.2.post1
  - itk-filtering==5.4.2.post1
  - itk-io==5.4.2.post1
  - itk-numerics==5.4.2.post1
  - itk-registration==5.4.2.post1
  - itk-segmentation==5.4.2.post1
  - itsdangerous==2.2.0
  - jinja2==3.1.6
  - joblib==1.4.2
  - json-tricks==3.17.3
  - jsonschema==4.23.0
  - jsonschema-specifications==2024.10.1
  - kiwisolver==1.4.8
  - lazy-loader==0.4
  - lmdb==1.6.2
  - lpips==0.1.4
  - mako==1.3.9
  - markdown==3.7
  - markupsafe==3.0.2
  - matplotlib==3.10.1
  - mlflow==2.20.3
  - mlflow-skinny==2.20.3
  - monai==1.4.0
  - mpmath==1.3.0
  - networkx==3.4.2
  - nibabel==5.3.2
  - ninja==1.11.1.3
  - nni==3.0
  - numcodecs==0.13.1
  - numpy==1.26.4
  - nvidia-cublas-cu12==12.4.5.8
  - nvidia-cuda-cupti-cu12==12.4.127
  - nvidia-cuda-nvrtc-cu12==12.4.127
  - nvidia-cuda-runtime-cu12==12.4.127
  - nvidia-cudnn-cu12==9.1.0.70
  - nvidia-cufft-cu12==11.2.1.3
  - nvidia-curand-cu12==10.3.5.147
  - nvidia-cusolver-cu12==11.6.1.9
  - nvidia-cusparse-cu12==12.3.1.170
  - nvidia-cusparselt-cu12==0.6.2
  - nvidia-ml-py==12.570.86
  - nvidia-nccl-cu12==2.21.5
  - nvidia-nvjitlink-cu12==12.4.127
  - nvidia-nvtx-cu12==12.4.127
  - omegaconf==2.3.0
  - onnx==1.17.0
  - onnxruntime==1.21.0
  - openslide-python==1.4.1
  - opentelemetry-api==1.30.0
  - opentelemetry-sdk==1.30.0
  - opentelemetry-semantic-conventions==0.51b0
  - optuna==4.2.1
  - orderedmultidict==1.0.1
  - pandas==2.2.3
  - pathlib2==2.3.7.post1
  - patsy==1.0.1
  - pillow==11.1.0
  - prettytable==3.15.1
  - protobuf==5.29.3
  - pyamg==5.2.1
  - pyarrow==19.0.1
  - pyasn1==0.6.1
  - pyasn1-modules==0.4.1
  - pydantic==2.10.6
  - pydantic-core==2.27.2
  - pydicom==3.0.1
  - pyjwt==2.9.0
  - pynrrd==1.1.3
  - pyparsing==3.2.1
  - pysocks==1.7.1
  - pythonwebhdfs==0.2.3
  - pytorch-ignite==0.4.11
  - pytorch-msssim==1.0.0
  - pytz==2025.1
  - pyyaml==6.0.2
  - referencing==0.36.2
  - regex==2024.11.6
  - requests==2.32.3
  - responses==0.25.6
  - rpds-py==0.23.1
  - rsa==4.9
  - safetensors==0.5.3
  - schema==0.7.7
  - scikit-image==0.25.2
  - scikit-learn==1.6.1
  - scipy==1.15.2
  - simplejson==3.20.1
  - smmap==5.0.2
  - soupsieve==2.6
  - sqlalchemy==2.0.38
  - sqlparse==0.5.3
  - statsmodels==0.14.4
  - sympy==1.13.1
  - tensorboard==2.19.0
  - tensorboard-data-server==0.7.2
  - tensorboardx==2.6.2.2
  - termcolor==2.5.0
  - threadpoolctl==3.5.0
  - tifffile==2025.2.18
  - tokenizers==0.19.1
  - torch==2.6.0
  - torchaudio==2.6.0
  - torchvision==0.21.0
  - tqdm==4.67.1
  - transformers==4.40.2
  - triton==3.2.0
  - typeguard==4.1.2
  - typing-extensions==4.12.2
  - tzdata==2025.1
  - urllib3==2.3.0
  - webcolors==24.11.1
  - websockets==15.0.1
  - werkzeug==3.1.3
  - wrapt==1.17.2
  - zarr==2.18.3
